name: Testing secret variables

on: 
  workflow_dispatch:
env:
  ACTIONS_STEP_DEBUG: true

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: "cheksing secret variable"
        run: |
          echo "Secret value : ${{ secrets.MY_KEY }}"
