name: Test user input work flow

on: 
  workflow_dispatch:
    inputs:
      number1:
        description: 'first number'
        default: '0'
        required: true
      number2:
        description: 'second number'
        default: '0'
        required: true

jobs:
  add_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: add number
        id: sum
        run: |
          echo "sum=$((${{ github.event.inputs.number1 }} + ${{ github.event.inputs.number2 }}))" >> $GITHUB_OUTPUT
          echo "${{ github.event.inputs.number1 }} + ${{ github.event.inputs.number2 }}"

      - name: Display sum
        run: echo "the sum of ${{ github.event.inputs.number1 }} and ${{ github.event.inputs.number2 }} is ${{ steps.sum.outputs.sum }}"
